### PR TITLE
add Makefile

### PR DESCRIPTION
**Pull request by faraco**
This Makefile will compile all source files to binary object with the same name as source file.

### CODE REVIEW

**Comment by schas002** [comment]
We just need to add about that to the docs for the stiristics.

**Comment by faraco** [comment]
and to be sure, change the description on how to use the Makefile if they on Linux or  Windows + cgywin?

**Comment by schas002** [comment]
@faraco Okay. For MinGW and Cygwin, what would the names be? `Lesson_*_*.exe`?

**Comment by faraco** [comment]
Well, if they got `gcc` and `make` in the PATH or %PATH%, then cd to the '$PROJECT/C/Stiristics_101/' and `make` will trigger the compilations for all source file.

**Pull request merged**
