### PR TITLE
Add about Makefile in C stiristics

### PR DESCRIPTION
**Pull request by schas002**
@faraco sent in a nice Makefile in #6. :3 

Next, add about the new makefile.

### CODE REVIEW

**Comment by faraco** [comment]
If on Ubuntu, I recommend truncate the installation commands with `sudo apt-get install build-essential`. You got the C build tools and other coreutils in one go.

**Comment by schas002** [comment]
Wait, lemme make a new PR... (Or you can make it yourself. 😀)

**Comment by faraco** [comment]
As long the repository inherits the repository Debian, the potential to use the same command is likely yes. For example, ToriOS.

**Comment by schas002** [comment]
Thanks, wizzwizz4! :sparkles:

**Pull request merged**
